INSERT INTO TU0003D.SANDWICHORDERDETAILS (AMOUNT, BREADTYPE, VEGETABLES, "COMMENT", PERSON, SANDWICHORDER, ID, SANDWICHNAME) VALUES (1, 'BROWN', 'Y', null, 1, 0, 0, 'poisson');
INSERT INTO TU0003D.SANDWICHORDERDETAILS (AMOUNT, BREADTYPE, VEGETABLES, "COMMENT", PERSON, SANDWICHORDER, ID, SANDWICHNAME) VALUES (1, 'WHITE', 'N', null, 4, 1, 1, 'viande');
